---
# Configures PostgreSQL client

- name: install postgresql client
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present  # won't update if done under an hour ago
  with_items:
    - postgresql-client
    - libpq-dev
    - python-psycopg2 # required for tools such as SQLAlchemy

- include: controller-user.yml
- include: app-user.yml
